spring:
  datasource:
    url: jdbc:mysql://moe-db-1.cdgugwuowxj4.ap-northeast-2.rds.amazonaws.com:3306/moe
    username: root
    password: kevin1104
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true

        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type: TRACE
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: a090ed16ad7cf9039104c87a03989c38
            client-secret: B7S3PhKTGSKJQ9T4fFO2ucBV6CXUFqXF
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post


          google:
            client-id: 56882231819-eler1td32o26rjorconut5jkdffasekf.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-name: Google

            scope:
              - email
              - profile

          naver:
            client-id: q6EE5D8e5hxql9xl1rzh
            client-secret: HTM61bxeWo
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


jwt:
  secret: THISISMOETESTKEYV0S2V5Rm9ySlRXdG9TZWNyZXQxM=
coolsms:
  api:
    #    외부에 노출되면 안된다해서 지우고 뒤에 푸시 테스트 필요시 말씀주십쇼
    key: ""
    secret: ""
    number: 01037764343

  #     url: jdbc:mysql://localhost:3306/test11
  #     username: root
  #     password: adsx123