spring:
  datasource:
    url: jdbc:mysql://moe-db-1.cdgugwuowxj4.ap-northeast-2.rds.amazonaws.com:3306/moe
    username: root
    password: kevin1104
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type: TRACE
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
kakao:
  client-id: YOUR_KAKAO_CLIENT_ID
  client-secret: YOUR_KAKAO_CLIENT_SECRET
  redirect-uri: http://localhost:8080/user/kakao/callback

naver:
  client-id: YOUR_NAVER_CLIENT_ID
  client-secret: YOUR_NAVER_CLIENT_SECRET
  redirect-uri: http://localhost:8080/user/naver/callback

google:
  client-id: YOUR_GOOGLE_CLIENT_ID
  client-secret: YOUR_GOOGLE_CLIENT_SECRET
  redirect-uri: http://localhost:8080/user/google/callback

jwt:
  secret: THISISMOETESTKEYV0S2V5Rm9ySlRXdG9TZWNyZXQxM=